name: Generate Pagespeed Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # every Sunday at midnight UTC
  push:

jobs:
  generate-metrics:
    name: Generate metrics
    runs-on: ubuntu-latest
    steps:
      - name: Generate PageSpeed card
        uses: lowlighter/metrics@latest
        with:
          filename: .github/assets/pagespeed-metrics.svg
          token: NOT_NEEDED
          committer_message: "docs(readme): update pagespeed metrics [skip ci]"
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          
          plugin_pagespeed_url: https://tg.toshiki.dev